# Generated by Django 3.2.8 on 2021-10-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0002_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last name'),
        ),
    ]
